### ISSUE TITLE
that's my code

### ISSUE THREAD

**Issue by nighthoodie** [ssbarnea/z264#1]
You should have probably asked before posting the code here. You are free to use the code and alter it for personal use, but to post it is something else altogether. It is free for personal use, but it is NOT open source (even if I made the source is available), yet. It cannot be forked without violating my copyright. I'm not sure how I feel about this.

Eliminate that brew setup stuff, plz. It is superfluous. The binary install section works fine (though there may be a couple minor bugs there, typos and maybe a missing quote mark, should be academic to fix this on the fly when it fails) and I'm working on the xcode/macports source install section (to make it completely automated once the user decides which way to install the dependencies). Brew is still in its infancy, is incomplete, unreliable, barely has any user support, if any at all, and leaves a complete mess on systems it is used on, and I really think it is only used because of ignorance of the availability of a superior, stable, mature and fully supported package management available to OS X, namely, MacPorts. Maybe in a few years Brew will mature, but I'd never use Brew (as it stands right now) in z264 because it will just cause more problems that it will solve. Of course you're welcome to use Brew yourself, but to tie it to this script is a bad idea.

The two parts that are incomplete are the source install section and the RAMdisk creation section, and I've documented where this is going in the script itself. Everything else works well (though the logic will likely go through a few stages to make it more efficient and resilient), and I've been using for my own needs for some time (and this has presented the issue of making the code more generic for other users and systems, and less customized for my own system, which, again, I've been mulling over how best to go about this without breaking it completely).

I really appreciate your enthusiasm, but you should really really really look before you leap (sorry for the tired idiom here, its late and I can't think of a better way t put it at the moment).

**Comment by ssbarnea** [comment]
I just seen your msg, and based on your feedback I think I will start from zero. I was looking for something that to contribute to instead of starting from scratch but it seems that we have too many problems to deal with.

Anyway a first test run on mkv test files from http://www.auby.no/files/video_tests/ gives 8/10 failures, destroying the original files.

BTW, before reading you msg I change the hyerlink to x264 from
http://apple.stackexchange.com/questions/118254/how-to-fully-automate-video-conversion-to-mp4-itunes-friendly-format/131655#131655

Can you please put the original one back? I cannot even find your original gits on google, maybe you removed it.

**Comment by ssbarnea** [comment]
BTW, I tried to contact you, but it seems that you give a contact information on your profile. 

I will remove this repo in a couple of hours.

**Comment by nighthoodie** [comment]
I'm not sure exactly what you mean by "destroying the files." All z264 will do is move the original files to the users Trash, where they should be perfectly intact. It will never "destroy" anything, so I'm not sure what you did there. Also, with mkv files, there is no actual transcoding. The resulting file will be rewrapped in mp4, and that is all that will happen to mkv. 

Ask Different is sometimes quite vexing. I cannot see any way to private message another user on the site. However, if you leave a comment under another user's answer or question, they will be notified by email by Ask Different. That's how I discovered you posted on git, I was notified that you posted a comment to my answer. 

Again, appreciate your enthusiasm, but you went a step to far without any authority. I had always intended to collaborate with other users, but felt the code was still in its infancy and this is why I never posted on git but instead on Pastebin.

> Can you please put the original one back? I cannot even find your original gits on google, maybe you removed it.

I don't understand what you're referring to or what you mean by this, or what it is that you're requesting.
